spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/quotation_db}
    username: ${SPRING_DATASOURCE_USERNAME:print3d}
    password: ${SPRING_DATASOURCE_PASSWORD:print3d}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    schemas: quotation_db
server:
  port: 8080
